providers = ['node']
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1741046653'

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'

[phases.setup]
nixPkgs = [
    'nodejs_18',
    'bun',
    'caddy'
]
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']
nixpkgsArchive = 'ffeebf0acf3ae8b29f8c7049cd911b9636efd7e7'

[phases.install]
dependsOn = ['setup']
cmds = ['bun i --no-save']
cacheDirectories = ['/root/.bun']
paths = ['/app/node_modules/.bin']

[phases.build]
dependsOn = ['install']
cmds = [
    'caddy run --config /app/Caddyfile & bun run build',
]
cacheDirectories = ['node_modules/.cache']

[start]
cmd = "caddy run --config /app/Caddyfile & bun start"
